version: '3.3'

services:
  # Servidor PHP
  php-fpm:
    build:
      args:
        user: ${SO_USER}
        uid: ${SO_USER_ID}
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ${APP_AlIAS}_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "${APP_PORT}:80"
    networks:
      laranet:
        ipv4_address: 172.100.0.9

  # redis
  redis:
    build:
        context: ./docker/redis
    restart: unless-stopped
    container_name: ${APP_AlIAS}_redis
    volumes:
      - ./docker/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laranet

networks:
  laranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24
